### ISSUE TITLE
Not running with realeased version of Angular 2 / Ionic 2

### ISSUE THREAD

**Issue by oliviercherrier** [vfdev-5/demo_background-geolocation#1]
Thank you very much for this first version. 

Based on this, I just finished implementation a new Ionic 2 project which include cordova-plugin-background-geolocation  of mauron85. [mauron85-background-geolocation-example-ionic2](https://github.com/oliviercherrier/mauron85-background-geolocation-example-ionic2)

**Comment by vfdev-5** [comment]
You're welcome.

As you, probably, remarked there are 2 branches in this repository : *master* and *ionic_v2* which represent Ionic code version 1 and version 2 (2.0.0-beta.6). It is possible that the latest version of Ionic 2 is now incompatible with their beta 6 version.

**Comment by oliviercherrier** [comment]
Yes, that's it. They have made numbers of modification from beta-6 to current version. 

So much modification encourage me to create a new project to integrate mauron85/cordova-plugin-background-geolocation.

I closed this issue because this message was mainly to say you a big thank you and to say that I reuse your code into my project,  even  if it is not a fork.

**Comment by vfdev-5** [comment]
Yes, feel free to reuse it as you like. This repository was just a demo/test for a PR to *ionic-native*. Good luck with quickly changing Ionic 2 :)
